
# GCC
# CXXFLAGS = -Wextra -Wall -std=gnu++11 -fno-exceptions -fno-threadsafe-statics
EXTRA_CXXFLAGS=-g3 -O0

CXXFLAGS=-D_GNU_SOURCE -Werror=return-type -std=gnu++17 -Wall -g3 -O0

# CLANG SANITIZE
# CXX=clang
# EXTRA_CXXFLAGS=-g3 -O0 -fsanitize=memory
# LDFLAGS = -lpthread -lstdc++
