
# GCC
# CXXFLAGS = -Wextra -Wall -std=gnu++11 -fno-exceptions -fno-threadsafe-statics
CXXFLAGS=-D_GNU_SOURCE -Werror=return-type -std=gnu++11 -Wall

# CLANG SANITIZE
# CXX=clang
# EXTRA_CXXFLAGS=-g3 -O0 -fsanitize=memory
# LDFLAGS = -lpthread -lstdc++
