# See https://github.com/bxparks/EpoxyDuino for documentation about this
# Makefile to compile and run Arduino programs natively on Linux or MacOS.

APP_NAME := local-tests
ARDUINO_LIBS := AUnit AceCommon AceTime TinyMqtt
include ../../../EpoxyDuino/EpoxyDuino.mk
